nelx = 3;
nely = 3;
multiple_load_cases = 3; % 为了示例目的，这里设定多重载荷情况的数量为 10

F = sparse( ...
    [2*(nely+1)*nelx+2, 2*(nely+1)*(nelx+1), 2*(nely+1)*nelx+2, 2*(nely+1)*(nelx+1)], ...
    [1, 2, 3, 3], ...
    [1, -1, 1, -2], ...
    2*(nely+1)*(nelx+1), ...
    multiple_load_cases);

full(F)
